### ISSUE TITLE
Nothing happens when downloadReleases() is called.

### ISSUE THREAD

**Issue by ghost** [terascope/fetch-github-release#103] opened 2020-08-09 12:27 UTC
My code:

![image](https://user-images.githubusercontent.com/57721560/89732065-f2d60e00-da43-11ea-8e3e-05707a41e70f.png)
![image](https://user-images.githubusercontent.com/57721560/89732068-f9648580-da43-11ea-842c-ad39b106cbeb.png)

The release asset trying to download:

https://github.com/cal3432/engineering-inc/releases/tag/v0.0.0
![image](https://user-images.githubusercontent.com/57721560/89732072-041f1a80-da44-11ea-867f-37d777705cf4.png)

**Comment by cal3432** [comment] 2020-08-09 12:28
![image](https://user-images.githubusercontent.com/57721560/89732073-1a2cdb00-da44-11ea-9e80-ffa08f4c84ad.png)

**Comment by cal3432** [comment] 2020-08-09 12:29
Temporarily using child_process.exec() to download.

**Comment by peterdemartini** [comment] 2020-08-10 01:23
@cal3432 I think the problem is your use of `indexOf`, if the search string is at the beginning of string it will return `0`, which means your code should be changed to `indexOf('...') >= 0`

**Comment by cal3432** [comment] 2020-08-10 07:10
Well, I'll fix it but it was the example on the npm page

**Comment by peterdemartini** [comment] 2021-03-01 15:13
I updated the README, closing this

**Closed by peterdemartini** 2021-03-01 15:13 UTC
